* Part 0

## Probability of having an empty bin when placing [`n`] balls in
[`n`] bins ##

Suppose there are [`m`] balls and [`n`] bins. What is the chance that there is an empty bin if [`m = n`] ?

Intuitively, one would expect this to be pretty close to 1 (that is,
pretty much certain), because the complementary event -- no empty bins
-- would occur only if every single bin received exactly one ball.

Let's analyze this latter probability. Imagine that the balls are
placed into random bins one ball at a time. Making the placement
sequential does not change the probabilities, but makes the analysis
easier.

The event whose probability we want to upper bound is the event that
no two balls land in the same bin. When there are two balls in the
same bin we say that this is a "collision". We are interested in
upper bounding the probability that no collisions occur as we place
the [`n`] balls into the [`n`] bins. 

Let's denote by [`E_i`] the event that the [`i`]'th ball does not
cause a collision (is placed in an empty bin). Let
[`C_i`] be the complement event where the [`i`]'th ball causes a collision.
We are interested in upper bounding the probability of the event that
there are no collision, which we shall denote by [`A`]

[`` A = E_1 \cap E_2 \cap \cdots \cap E_n ``]

Computing this probability serially corresponds to using the chain
rule in the following way:

*(1)* [`` P(A) = P(E_1)\times P(E_2|E_1)
P(E_3|E_1 \cap E_2) \times \cdots \times P(E_n|E_1 \cap E_2 \cap \cdots E_{n-1} ``]

* Part 1
We start by rewriting *(1)* in a simpler form. First, you probably
know that the sum [`2+3+4+5+6`] can be written as [`\sum_{i=2}^6 i`].
In a similar way, we have that
\[\prod_{i=1}^3 i^2 = 1^2 \times 2^2 \times 3^2 = 1 \times 4 \times 9
= 36`].

Write the expanded expression for [`\prod_{i=3}^4 (1-i/5)`]
[_________]{"(1-3/5)(1-4/5)"}

* Part 2
Similar notation exists for the union of many sets:
[`` \bigcup_{i=1}^n A_i = A_1 \cup A_2 \cup \cdots \cup A_n ``]
And for the intersection of many sets
[`` \bigcap_{i=1}^n A_i = A_1 \cap A_2 \cap \cdots \cap A_n ``]

Using these notational shortcuts we can rewrite Equation *(1)* as:
*(1.5)* [``P(A)=P\left( \bigcap_{j=1}^n E_j \right) =
\prod_{i=1}^n P \left(E_i \left| \bigcap_{j=1}^{i-1} E_j
\right. \right) ``]

We will now compute a bound for each of the [`n`] factors and then
bound the product.
* Part 3
Consider the first ball. When it is placed none of the bins is
occupied. A collision is therefor impossible. In other words, the
probability that the first ball does *not* create a colliosion is 
*(2)* [`P(E_1)=`]*[  1]{1}*
* Answers of student jmc001. 10 attempts lasting 15.4 minutes, ending in sucess
** All but last attempt
  0:	  1	 0.0	0	1-(1/n)
  1:	  1	 0.1	0	n-1
  2:	  1	 0.2	1	1
  3:	  1	 0.3	0	n
  4:	  1	 1.1	0	0
  5:	  1	 2.9	0	100
  6:	  1	11.2	0	n-1
  7:	  1	11.3	1	1
  8:	  1	15.3	0	n-1
**   9:	  1	15.4	1	1

* Part 4
Consider the second ball. At this point exactly one bin is occupied
(with the first ball). There is thus [`1`] bin that will cause a
collision and [`n-1`] bins that will not. As we are choosing each bin
with probability [`1/n`], the probability that the second ball does
not cause a collision is  
*(3)* [`P(E_2|E_1)=`] *[ 2]{(1-1/n)}*
* Answers of student jmc001.  5 attempts lasting 13.8 minutes, ending in sucess
** All but last attempt
  0:	  2	 9.0	0	m-1
  1:	  2	 9.9	0	n-1/m
  2:	  2	10.5	0	1-(2/n)
  3:	  2	22.1	0	n-1
**   4:	  2	22.9	1	1-(1/n)

* Part 5
Consider the third ball. At this point there are already two balls on
the board and we assume that they have not collided. Therefor there
are [`n-2`] empty cells and the probability that the thid ball falls
into one of these cells is:

*(4)*  [`P(E_3|E_1 \cap E_2)=`]*[  3]{(1-2/n)}*
* Answers of student jmc001.  3 attempts lasting 0.2 minutes, ending in sucess
** All but last attempt
  0:	  3	27.9	0	1-(1/n)
  1:	  3	28.1	0	1-(3/n)
**   2:	  3	28.1	1	1-(2/n)

* Part 6
More generally, consider the probability that the placement of the
[`k`] th ball does not cause a collision, given that the previous
[`k-1`] balls had no collision. In this situation exactly [`k-1`] of
the bins are empty and therefor

*(5)* *[  4]{(1-(k-1)/n)}*
* Answers of student jmc001. 15 attempts lasting 31.0 minutes, ending in sucess
** All but last attempt
  0:	  4	34.8	0	1-(n-1/n)
  1:	  4	34.9	0	1-((n-1)/n)  <----- closest
  2:	  4	38.0	0	n!
  3:	  4	38.7	0	1/n
  4:	  4	44.1	0	1-n!
  5:	  4	44.5	0	n!/(k!(n-k!))
  6:	  4	47.9	0	(n-1)/n
  7:	  4	49.1	0	1-n!/n^n
  8:	  4	49.2	0	1-n!/n
  9:	  4	51.5	0	1-(k/n)
 10:	  4	51.9	0	1/(n-k)
 11:	  4	60.8	0	k/n!
 12:	  4	61.2	0	(k-1)/n
 13:	  4	65.5	0	1-(k-1/n)
**  14:	  4	65.7	1	1-((k-1)/n)
* HINTS
** HINT: 
Your answer of [`1-(n-1)/n`] is the correct answer to the question
"What is the probability that the last ball (the [`n`]th ball) falls
in an empty bin". However, here we are asking about the [`k`]'th ball,
where [`k`] can be any number between [`1`] and [`n`]. Assuming
[`n>10`], what is the probability that the [`10`]th ball falls in an
empty bin? [__________]{1-(9/n)}

* Part 7
We now come back to computing the product defined in Equations *(1)*
and *(1.5)*. Can you simplify the expression:
[`` \prod_{k=1}^n \left(1-\frac{k-1}{n}\right) = \prod_{k=1}^n
\frac{n-k+1}{n}``]
Hint: it is enough to use exponentiation [`` i^j``] and the factorial
[``i!=\prod_{j=1}^i j ``] 
*(6)* *[  5]{n!/n^n}*
* Answers of student jmc001.  2 attempts lasting 26.9 minutes, ending in sucess
** All but last attempt
  0:	  5	11.2	0	1/2^(n/2)
**   1:	  5	38.0	1	n!/n^n

* Part 8
 (write the answer in [`n`] only).

This probability is miniscule. To show this, we need to upper bound *(6)*.

We start by upper bounding *(5)*.  Recall the inequality [`1+x \leq e^x`]. Plugging [`-\frac{k-1}{n}`] in for [`x`], gives us an upper bound on *(B)*
that is 

*(7)* ['P(E_k) \leq `] *[  6]{Formula("e^(-(k-1)/n)")}*
* Answers of student jmc001.  3 attempts lasting 2.7 minutes, ending in sucess
** All but last attempt
  0:	  6	67.7	0	e^((k-1)/n)
  1:	  6	70.4	0	1-((k-1)/n)
**   2:	  6	70.4	1	e^(-(k-1)/n)

* Part
In equation *(7)* we upper bounded the probability  that the [`k`]th ball
lands in an empty bin. We now want to upper bound the probability
that *all* [`n`] balls land in an empty bin. Equation *(1.5)* tell us
that this is equal to the product [`\prod_{i=k}^n P(E_k)`]

Recall that the product of exponentials is equal to the exponential
of the sum. For example:
[``e^a e^b = e^{a+b}``]

Based on this equality and on your solution to *(7)* write an upper bound on
Equation *(1.5)* in the form of a sum:
[`` P\left( \bigcap_{j=1}^n E_j \right) = e^{\sum_{k=1}^n a_k} ``]
[`a_k=`][_______]{(n-k+1)/n}

* Part
Now, simplify the expression [`\sum_{k=1}^n a_k`]. Recall that 
[`` \sum_{i=1}^n i = \frac{(n+1)n}{2}  ``]
*(8)* [`` \sum_{k=1}^n a_k = ``][_________]{-\frac{n+1}{2}}

** HINT:
The product of two exponentials with the same basis is equal to the
exponent of the sum. For example:
[`2^5 \times 2^3 = 2^{5+3} = 256`]
[`e^{\pi} \times e^2 = e^{2\pi}]

Write the following expression in the form [`e^(\sum \cdot)`]

[` \prod_{k=2}^n e^(-(k-1)/n)'] = [_______________]{"e^(\sum_{k=2}^n
(k-1)/n)"}

* Part 9
Finally, put Equation *(8)* back in the exponent to find the upper
bound on [`P(A)`]
[`P(A) \leq `] *[  7]{Formula("e^(-(n+1)/2)")}*
* Answers of student jmc001. 30 attempts lasting 54.0 minutes, ending in failure
** All but last attempt
  0:	  7	67.7	0	n!/n^n
  1:	  7	70.4	0	e^(-(k/n))
  2:	  7	70.7	0	e^(-(k!/n^n))
  3:	  7	70.8	0	e^(k!/n^n)
  4:	  7	72.5	0	e^(k^n)
  5:	  7	73.7	0	e^(n!/n^n)
  6:	  7	76.2	0	e^(n!/k!(n-k)!)
  7:	  7	76.4	0	e^(n!/(k!(n-k!))
  8:	  7	76.5	0	e^(n!/(k!(n-k!)))
  9:	  7	81.4	0	1/k^(k/2)
 10:	  7	81.7	0	k^(k/2)
 11:	  7	82.4	0	1/ek^k
 12:	  7	82.7	0	1/(e(k^k))
 13:	  7	83.6	0	(1-(1/n))^n-k
 14:	  7	83.8	0	(1-(1/n))^(n-k)
 15:	  7	84.4	0	1/n^k
 16:	  7	84.5	0	1/n^2
 17:	  7	87.1	0	[e^(-(k-1)/n)]*(n!/n^n)
 18:	  7	87.6	0	[e^(-(k-1)/n)]*[1-((k-1)/n)]
 19:	  7	88.8	0	[e^(-(k-1)/n)]*e^k
 20:	  7	94.1	0	(-(k-1)/n)*[n!/n^n]
 21:	  7	94.4	0	e^{(-(k-1)/n)*[n!/n^n]}
 22:	  7	99.1	0	[e^(n!/n^n)]*[e^(-(k-1)/n)]
 23:	  7	110.2	0	[(ne/k)^k]*(1/n)^k
 24:	  7	111.3	0	[(e/k)^k]*1/(1-(e/k))
 25:	  7	111.6	0	[(e/k)^k]*[1/(1-(e/k))]
 26:	  7	113.7	0	e^(-[m(m-1)]/2n)
 27:	  7	121.3	0	[1-((k-1)/n)]*[n!/n^n]
 28:	  7	121.5	0	e^[1-((k-1)/n)]*[n!/n^n]
**  29:	  7	121.7	0	e^{[1-((k-1)/n)]*[n!/n^n]}

