SELECT 'CSE21_achievement' as '';
select * from CSE21_achievement limit 1;
SELECT 'CSE21_achievement_user' as '';
select * from CSE21_achievement_user limit 1;
SELECT 'CSE21_global_user_achievement' as '';
select * from CSE21_global_user_achievement limit 1;
SELECT 'CSE21_key' as '';
select * from CSE21_key limit 1;
SELECT 'CSE21_password' as '';
select * from CSE21_password limit 1;
SELECT 'CSE21_past_answer' as '';
select * from CSE21_past_answer limit 1;
SELECT 'CSE21_permission' as '';
select * from CSE21_permission limit 1;
SELECT 'CSE21_problem' as '';
select * from CSE21_problem limit 1;
SELECT 'CSE21_problem_user' as '';
select * from CSE21_problem_user limit 1;
SELECT 'CSE21_set' as '';
select * from CSE21_set limit 1;
SELECT 'CSE21_set_locations' as '';
select * from CSE21_set_locations limit 1;
SELECT 'CSE21_set_locations_user' as '';
select * from CSE21_set_locations_user limit 1;
SELECT 'CSE21_set_user' as '';
select * from CSE21_set_user limit 1;
SELECT 'CSE21_setting' as '';
select * from CSE21_setting limit 1;
SELECT 'CSE21_user' as '';
select * from CSE21_user limit 1;
SELECT 'CompoundProblems_achievement' as '';
select * from CompoundProblems_achievement limit 1;
SELECT 'CompoundProblems_achievement_user' as '';
select * from CompoundProblems_achievement_user limit 1;
SELECT 'CompoundProblems_global_user_achievement' as '';
select * from CompoundProblems_global_user_achievement limit 1;
SELECT 'CompoundProblems_key' as '';
select * from CompoundProblems_key limit 1;
SELECT 'CompoundProblems_password' as '';
select * from CompoundProblems_password limit 1;
SELECT 'CompoundProblems_past_answer' as '';
select * from CompoundProblems_past_answer limit 1;
SELECT 'CompoundProblems_permission' as '';
select * from CompoundProblems_permission limit 1;
SELECT 'CompoundProblems_problem' as '';
select * from CompoundProblems_problem limit 1;
SELECT 'CompoundProblems_problem_user' as '';
select * from CompoundProblems_problem_user limit 1;
SELECT 'CompoundProblems_set' as '';
select * from CompoundProblems_set limit 1;
SELECT 'CompoundProblems_set_locations' as '';
select * from CompoundProblems_set_locations limit 1;
SELECT 'CompoundProblems_set_locations_user' as '';
select * from CompoundProblems_set_locations_user limit 1;
SELECT 'CompoundProblems_set_user' as '';
select * from CompoundProblems_set_user limit 1;
SELECT 'CompoundProblems_setting' as '';
select * from CompoundProblems_setting limit 1;
SELECT 'CompoundProblems_user' as '';
select * from CompoundProblems_user limit 1;
SELECT 'OPL_DBchapter' as '';
select * from OPL_DBchapter limit 1;
SELECT 'OPL_DBsection' as '';
select * from OPL_DBsection limit 1;
SELECT 'OPL_DBsubject' as '';
select * from OPL_DBsubject limit 1;
SELECT 'OPL_author' as '';
select * from OPL_author limit 1;
SELECT 'OPL_chapter' as '';
select * from OPL_chapter limit 1;
SELECT 'OPL_keyword' as '';
select * from OPL_keyword limit 1;
SELECT 'OPL_morelt' as '';
select * from OPL_morelt limit 1;
SELECT 'OPL_morelt_pgfile' as '';
select * from OPL_morelt_pgfile limit 1;
SELECT 'OPL_path' as '';
select * from OPL_path limit 1;
SELECT 'OPL_pgfile' as '';
select * from OPL_pgfile limit 1;
SELECT 'OPL_pgfile_keyword' as '';
select * from OPL_pgfile_keyword limit 1;
SELECT 'OPL_pgfile_problem' as '';
select * from OPL_pgfile_problem limit 1;
SELECT 'OPL_problem' as '';
select * from OPL_problem limit 1;
SELECT 'OPL_section' as '';
select * from OPL_section limit 1;
SELECT 'OPL_textbook' as '';
select * from OPL_textbook limit 1;
SELECT 'Test_Course2_achievement' as '';
select * from Test_Course2_achievement limit 1;
SELECT 'Test_Course2_achievement_user' as '';
select * from Test_Course2_achievement_user limit 1;
SELECT 'Test_Course2_global_user_achievement' as '';
select * from Test_Course2_global_user_achievement limit 1;
SELECT 'Test_Course2_key' as '';
select * from Test_Course2_key limit 1;
SELECT 'Test_Course2_password' as '';
select * from Test_Course2_password limit 1;
SELECT 'Test_Course2_past_answer' as '';
select * from Test_Course2_past_answer limit 1;
SELECT 'Test_Course2_permission' as '';
select * from Test_Course2_permission limit 1;
SELECT 'Test_Course2_problem' as '';
select * from Test_Course2_problem limit 1;
SELECT 'Test_Course2_problem_user' as '';
select * from Test_Course2_problem_user limit 1;
SELECT 'Test_Course2_set' as '';
select * from Test_Course2_set limit 1;
SELECT 'Test_Course2_set_locations' as '';
select * from Test_Course2_set_locations limit 1;
SELECT 'Test_Course2_set_locations_user' as '';
select * from Test_Course2_set_locations_user limit 1;
SELECT 'Test_Course2_set_user' as '';
select * from Test_Course2_set_user limit 1;
SELECT 'Test_Course2_setting' as '';
select * from Test_Course2_setting limit 1;
SELECT 'Test_Course2_user' as '';
select * from Test_Course2_user limit 1;
SELECT 'Test_Course_achievement' as '';
select * from Test_Course_achievement limit 1;
SELECT 'Test_Course_achievement_user' as '';
select * from Test_Course_achievement_user limit 1;
SELECT 'Test_Course_global_user_achievement' as '';
select * from Test_Course_global_user_achievement limit 1;
SELECT 'Test_Course_key' as '';
select * from Test_Course_key limit 1;
SELECT 'Test_Course_password' as '';
select * from Test_Course_password limit 1;
SELECT 'Test_Course_past_answer' as '';
select * from Test_Course_past_answer limit 1;
SELECT 'Test_Course_permission' as '';
select * from Test_Course_permission limit 1;
SELECT 'Test_Course_problem' as '';
select * from Test_Course_problem limit 1;
SELECT 'Test_Course_problem_user' as '';
select * from Test_Course_problem_user limit 1;
SELECT 'Test_Course_set' as '';
select * from Test_Course_set limit 1;
SELECT 'Test_Course_set_locations' as '';
select * from Test_Course_set_locations limit 1;
SELECT 'Test_Course_set_locations_user' as '';
select * from Test_Course_set_locations_user limit 1;
SELECT 'Test_Course_set_user' as '';
select * from Test_Course_set_user limit 1;
SELECT 'Test_Course_setting' as '';
select * from Test_Course_setting limit 1;
SELECT 'Test_Course_user' as '';
select * from Test_Course_user limit 1;
SELECT 'UCSD_CSE103_achievement' as '';
select * from UCSD_CSE103_achievement limit 1;
SELECT 'UCSD_CSE103_achievement_user' as '';
select * from UCSD_CSE103_achievement_user limit 1;
SELECT 'UCSD_CSE103_global_user_achievement' as '';
select * from UCSD_CSE103_global_user_achievement limit 1;
SELECT 'UCSD_CSE103_key' as '';
select * from UCSD_CSE103_key limit 1;
SELECT 'UCSD_CSE103_password' as '';
select * from UCSD_CSE103_password limit 1;
SELECT 'UCSD_CSE103_past_answer' as '';
select * from UCSD_CSE103_past_answer limit 1;
SELECT 'UCSD_CSE103_permission' as '';
select * from UCSD_CSE103_permission limit 1;
SELECT 'UCSD_CSE103_problem' as '';
select * from UCSD_CSE103_problem limit 1;
SELECT 'UCSD_CSE103_problem_user' as '';
select * from UCSD_CSE103_problem_user limit 1;
SELECT 'UCSD_CSE103_set' as '';
select * from UCSD_CSE103_set limit 1;
SELECT 'UCSD_CSE103_set_locations' as '';
select * from UCSD_CSE103_set_locations limit 1;
SELECT 'UCSD_CSE103_set_locations_user' as '';
select * from UCSD_CSE103_set_locations_user limit 1;
SELECT 'UCSD_CSE103_set_user' as '';
select * from UCSD_CSE103_set_user limit 1;
SELECT 'UCSD_CSE103_setting' as '';
select * from UCSD_CSE103_setting limit 1;
SELECT 'UCSD_CSE103_user' as '';
select * from UCSD_CSE103_user limit 1;
SELECT 'admin_achievement' as '';
select * from admin_achievement limit 1;
SELECT 'admin_achievement_user' as '';
select * from admin_achievement_user limit 1;
SELECT 'admin_global_user_achievement' as '';
select * from admin_global_user_achievement limit 1;
SELECT 'admin_key' as '';
select * from admin_key limit 1;
SELECT 'admin_password' as '';
select * from admin_password limit 1;
SELECT 'admin_past_answer' as '';
select * from admin_past_answer limit 1;
SELECT 'admin_permission' as '';
select * from admin_permission limit 1;
SELECT 'admin_problem' as '';
select * from admin_problem limit 1;
SELECT 'admin_problem_user' as '';
select * from admin_problem_user limit 1;
SELECT 'admin_set' as '';
select * from admin_set limit 1;
SELECT 'admin_set_locations' as '';
select * from admin_set_locations limit 1;
SELECT 'admin_set_locations_user' as '';
select * from admin_set_locations_user limit 1;
SELECT 'admin_set_user' as '';
select * from admin_set_user limit 1;
SELECT 'admin_setting' as '';
select * from admin_setting limit 1;
SELECT 'admin_user' as '';
select * from admin_user limit 1;
SELECT 'cse101_achievement' as '';
select * from cse101_achievement limit 1;
SELECT 'cse101_achievement_user' as '';
select * from cse101_achievement_user limit 1;
SELECT 'cse101_global_user_achievement' as '';
select * from cse101_global_user_achievement limit 1;
SELECT 'cse101_key' as '';
select * from cse101_key limit 1;
SELECT 'cse101_password' as '';
select * from cse101_password limit 1;
SELECT 'cse101_past_answer' as '';
select * from cse101_past_answer limit 1;
SELECT 'cse101_permission' as '';
select * from cse101_permission limit 1;
SELECT 'cse101_problem' as '';
select * from cse101_problem limit 1;
SELECT 'cse101_problem_user' as '';
select * from cse101_problem_user limit 1;
SELECT 'cse101_set' as '';
select * from cse101_set limit 1;
SELECT 'cse101_set_locations' as '';
select * from cse101_set_locations limit 1;
SELECT 'cse101_set_locations_user' as '';
select * from cse101_set_locations_user limit 1;
SELECT 'cse101_set_user' as '';
select * from cse101_set_user limit 1;
SELECT 'cse101_setting' as '';
select * from cse101_setting limit 1;
SELECT 'cse101_user' as '';
select * from cse101_user limit 1;
SELECT 'demo_achievement' as '';
select * from demo_achievement limit 1;
SELECT 'demo_achievement_user' as '';
select * from demo_achievement_user limit 1;
SELECT 'demo_course_achievement' as '';
select * from demo_course_achievement limit 1;
SELECT 'demo_course_achievement_user' as '';
select * from demo_course_achievement_user limit 1;
SELECT 'demo_course_global_user_achievement' as '';
select * from demo_course_global_user_achievement limit 1;
SELECT 'demo_course_key' as '';
select * from demo_course_key limit 1;
SELECT 'demo_course_password' as '';
select * from demo_course_password limit 1;
SELECT 'demo_course_past_answer' as '';
select * from demo_course_past_answer limit 1;
SELECT 'demo_course_permission' as '';
select * from demo_course_permission limit 1;
SELECT 'demo_course_problem' as '';
select * from demo_course_problem limit 1;
SELECT 'demo_course_problem_user' as '';
select * from demo_course_problem_user limit 1;
SELECT 'demo_course_set' as '';
select * from demo_course_set limit 1;
SELECT 'demo_course_set_locations' as '';
select * from demo_course_set_locations limit 1;
SELECT 'demo_course_set_locations_user' as '';
select * from demo_course_set_locations_user limit 1;
SELECT 'demo_course_set_user' as '';
select * from demo_course_set_user limit 1;
SELECT 'demo_course_setting' as '';
select * from demo_course_setting limit 1;
SELECT 'demo_course_user' as '';
select * from demo_course_user limit 1;
SELECT 'demo_global_user_achievement' as '';
select * from demo_global_user_achievement limit 1;
SELECT 'demo_key' as '';
select * from demo_key limit 1;
SELECT 'demo_password' as '';
select * from demo_password limit 1;
SELECT 'demo_past_answer' as '';
select * from demo_past_answer limit 1;
SELECT 'demo_permission' as '';
select * from demo_permission limit 1;
SELECT 'demo_problem' as '';
select * from demo_problem limit 1;
SELECT 'demo_problem_user' as '';
select * from demo_problem_user limit 1;
SELECT 'demo_set' as '';
select * from demo_set limit 1;
SELECT 'demo_set_locations' as '';
select * from demo_set_locations limit 1;
SELECT 'demo_set_locations_user' as '';
select * from demo_set_locations_user limit 1;
SELECT 'demo_set_user' as '';
select * from demo_set_user limit 1;
SELECT 'demo_setting' as '';
select * from demo_setting limit 1;
SELECT 'demo_user' as '';
select * from demo_user limit 1;
SELECT 'depths' as '';
select * from depths limit 1;
SELECT 'location_addresses' as '';
select * from location_addresses limit 1;
SELECT 'locations' as '';
select * from locations limit 1;
